Check to run even if fails

diff --git a/.github/workflows/jusit.yml b/.github/workflows/jusit.yml
--- a/.github/workflows/jusit.yml
+++ b/.github/workflows/jusit.yml
@@ -13,6 +13,8 @@ jobs:
   build:
     runs-on: ubuntu-latest
 
+    continue-on-error: true
+
     steps:
       - uses: actions/checkout@v4
 
@@ -23,11 +25,16 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: '3.10'
-        continue-on-error: true
       - run: |
           pip install -q -r requirements.txt
-          echo '\n\n'
+          echo "\n\n"
+          # export FOO=bar
           python selenium-crawler.py
+          # if [ $? -eq 0 ]; then
+          #   echo "Python script succeeded"
+          # else
+          #   echo "Python script failed"
+          # fi
 
       - name: Archive production artifacts
         uses: actions/upload-artifact@v3
